#ifndef __CONST_SETPOINT_INTERVAL__
#define __CONST_SETPOINT_INTERVAL__

#define KOEF_TT_MIN                   1
#define KOEF_TT_MAX                   2000

#define KOEF_TN_MIN                   50
#define KOEF_TN_MAX                   1800

#define SETPOINT_GRUPA_USTAVOK_MIN    1
#define SETPOINT_GRUPA_USTAVOK_MAX    4

#define TYPE_MTZ_SIMPLE                0
#define TYPE_MTZ_DIRECTIONAL           1
#define TYPE_MTZ_VOLTAGE               2
#define TYPE_MTZ_DEPENDENT_A           3
#define TYPE_MTZ_DEPENDENT_B           4
#define TYPE_MTZ_DEPENDENT_C           5
#define TYPE_MTZ_DEPENDENT_RT_80       6
#define TYPE_MTZ_DEPENDENT_RTV_I       7

#define SETPOINT_MTZ1_MIN             500
#define SETPOINT_MTZ1_MAX             150000

#define SETPOINT_MTZ1_N_VPERED_MIN    500
#define SETPOINT_MTZ1_N_VPERED_MAX    150000

#define SETPOINT_MTZ1_N_NAZAD_MIN    500
#define SETPOINT_MTZ1_N_NAZAD_MAX    150000

#define SETPOINT_MTZ1_ANGLE_MIN      0
#define SETPOINT_MTZ1_ANGLE_MAX      90

#define SETPOINT_MTZ1_PO_NAPRUZI_MIN 500
#define SETPOINT_MTZ1_PO_NAPRUZI_MAX 150000

#define SETPOINT_MTZ1_U_MIN          2000
#define SETPOINT_MTZ1_U_MAX          150000

#define SETPOINT_MTZ2_MIN            500
#define SETPOINT_MTZ2_MAX            150000

#define SETPOINT_MTZ2_N_VPERED_MIN    500
#define SETPOINT_MTZ2_N_VPERED_MAX    150000

#define SETPOINT_MTZ2_N_NAZAD_MIN    500
#define SETPOINT_MTZ2_N_NAZAD_MAX    150000

#define SETPOINT_MTZ2_ANGLE_MIN      0
#define SETPOINT_MTZ2_ANGLE_MAX      90

#define SETPOINT_MTZ2_PO_NAPRUZI_MIN 500
#define SETPOINT_MTZ2_PO_NAPRUZI_MAX 150000

#define SETPOINT_MTZ2_U_MIN          2000
#define SETPOINT_MTZ2_U_MAX          150000

#define SETPOINT_MTZ3_MIN             500
#define SETPOINT_MTZ3_MAX             150000

#define SETPOINT_MTZ3_N_VPERED_MIN    500
#define SETPOINT_MTZ3_N_VPERED_MAX    150000

#define SETPOINT_MTZ3_N_NAZAD_MIN    500
#define SETPOINT_MTZ3_N_NAZAD_MAX    150000

#define SETPOINT_MTZ3_ANGLE_MIN      0
#define SETPOINT_MTZ3_ANGLE_MAX      90

#define SETPOINT_MTZ3_PO_NAPRUZI_MIN 500
#define SETPOINT_MTZ3_PO_NAPRUZI_MAX 150000

#define SETPOINT_MTZ3_U_MIN          2000
#define SETPOINT_MTZ3_U_MAX          150000

#define SETPOINT_MTZ4_MIN             500
#define SETPOINT_MTZ4_MAX             150000

#define SETPOINT_MTZ4_N_VPERED_MIN    500
#define SETPOINT_MTZ4_N_VPERED_MAX    150000

#define SETPOINT_MTZ4_N_NAZAD_MIN    500
#define SETPOINT_MTZ4_N_NAZAD_MAX    150000

#define SETPOINT_MTZ4_ANGLE_MIN      0
#define SETPOINT_MTZ4_ANGLE_MAX      90

#define SETPOINT_MTZ4_PO_NAPRUZI_MIN 500
#define SETPOINT_MTZ4_PO_NAPRUZI_MAX 150000

#define SETPOINT_MTZ4_U_MIN          2000
#define SETPOINT_MTZ4_U_MAX          150000

#define TIMEOUT_MTZ1_MIN                        0
#define TIMEOUT_MTZ1_MAX                        32000

#define TIMEOUT_MTZ1_N_VPERED_MIN               0
#define TIMEOUT_MTZ1_N_VPERED_MAX               32000

#define TIMEOUT_MTZ1_N_NAZAD_MIN                0
#define TIMEOUT_MTZ1_N_NAZAD_MAX                32000

#define TIMEOUT_MTZ1_PO_NAPRUZI_MIN             0
#define TIMEOUT_MTZ1_PO_NAPRUZI_MAX             32000

#define TIMEOUT_MTZ2_MIN                        0
#define TIMEOUT_MTZ2_MAX                        300000

#define TIMEOUT_MTZ2_PR_MIN                     200
#define TIMEOUT_MTZ2_PR_MAX                     5000

#define TIMEOUT_MTZ2_N_VPERED_MIN               0
#define TIMEOUT_MTZ2_N_VPERED_MAX               300000

#define TIMEOUT_MTZ2_N_VPERED_PR_MIN            200
#define TIMEOUT_MTZ2_N_VPERED_PR_MAX            5000

#define TIMEOUT_MTZ2_N_NAZAD_MIN                0
#define TIMEOUT_MTZ2_N_NAZAD_MAX                300000

#define TIMEOUT_MTZ2_N_NAZAD_PR_MIN             200
#define TIMEOUT_MTZ2_N_NAZAD_PR_MAX             5000

#define TIMEOUT_MTZ2_PO_NAPRUZI_MIN             0
#define TIMEOUT_MTZ2_PO_NAPRUZI_MAX             300000

#define TIMEOUT_MTZ2_PO_NAPRUZI_PR_MIN          200
#define TIMEOUT_MTZ2_PO_NAPRUZI_PR_MAX          5000

#define TIMEOUT_MTZ2_VVID_PR_MIN                200
#define TIMEOUT_MTZ2_VVID_PR_MAX                5000

#define TIMEOUT_MTZ3_MIN                        0
#define TIMEOUT_MTZ3_MAX                        300000

#define TIMEOUT_MTZ3_PR_MIN                     200
#define TIMEOUT_MTZ3_PR_MAX                     5000

#define TIMEOUT_MTZ3_N_VPERED_MIN               0
#define TIMEOUT_MTZ3_N_VPERED_MAX               300000

#define TIMEOUT_MTZ3_N_VPERED_PR_MIN            200
#define TIMEOUT_MTZ3_N_VPERED_PR_MAX            5000

#define TIMEOUT_MTZ3_N_NAZAD_MIN                0
#define TIMEOUT_MTZ3_N_NAZAD_MAX                300000

#define TIMEOUT_MTZ3_N_NAZAD_PR_MIN             200
#define TIMEOUT_MTZ3_N_NAZAD_PR_MAX             5000

#define TIMEOUT_MTZ3_PO_NAPRUZI_MIN             0
#define TIMEOUT_MTZ3_PO_NAPRUZI_MAX             300000

#define TIMEOUT_MTZ3_PO_NAPRUZI_PR_MIN          200
#define TIMEOUT_MTZ3_PO_NAPRUZI_PR_MAX          5000

#define TIMEOUT_MTZ3_VVID_PR_MIN                200
#define TIMEOUT_MTZ3_VVID_PR_MAX                5000

#define TIMEOUT_MTZ4_MIN                        0
#define TIMEOUT_MTZ4_MAX                        300000

#define TIMEOUT_MTZ4_N_VPERED_MIN               0
#define TIMEOUT_MTZ4_N_VPERED_MAX               300000

#define TIMEOUT_MTZ4_N_NAZAD_MIN                0
#define TIMEOUT_MTZ4_N_NAZAD_MAX                300000

#define TIMEOUT_MTZ4_PO_NAPRUZI_MIN             0
#define TIMEOUT_MTZ4_PO_NAPRUZI_MAX             300000

#define TIMEOUT_APV1_MIN              100
#define TIMEOUT_APV1_MAX              200000

#define TIMEOUT_APV2_MIN              100
#define TIMEOUT_APV2_MAX              200000

#define TIMEOUT_APV3_MIN              100
#define TIMEOUT_APV3_MAX              200000

#define TIMEOUT_APV4_MIN              100
#define TIMEOUT_APV4_MAX              200000

#define TIMEOUT_APV_BLOCK_VID_APV1_MIN  200
#define TIMEOUT_APV_BLOCK_VID_APV1_MAX  200000

#define TIMEOUT_APV_BLOCK_VID_APV2_MIN  200
#define TIMEOUT_APV_BLOCK_VID_APV2_MAX  200000

#define TIMEOUT_APV_BLOCK_VID_APV3_MIN  200
#define TIMEOUT_APV_BLOCK_VID_APV3_MAX  200000

#define TIMEOUT_APV_BLOCK_VID_APV4_MIN  200
#define TIMEOUT_APV_BLOCK_VID_APV4_MAX  200000

#define TIMEOUT_APV_BLOCK_VID_VV_MIN  200
#define TIMEOUT_APV_BLOCK_VID_VV_MAX  200000

#define SETPOINT_UROV_MIN             250
#define SETPOINT_UROV_MAX             5000

#define TIMEOUT_UROV1_MIN             0
#define TIMEOUT_UROV1_MAX             32000

#define TIMEOUT_UROV2_MIN             0
#define TIMEOUT_UROV2_MAX             32000

#define SETPOINT_ZOP_MIN              10
#define SETPOINT_ZOP_MAX              1000

#define TIMEOUT_ZOP_MIN               0
#define TIMEOUT_ZOP_MAX               32000

#define SETPOINT_UMIN1_MIN            14000
#define SETPOINT_UMIN1_MAX            110000

#define SETPOINT_UMIN1_IBLK_MIN       250
#define SETPOINT_UMIN1_IBLK_MAX       5000

#define SETPOINT_UMIN2_MIN            14000
#define SETPOINT_UMIN2_MAX            110000

#define SETPOINT_UMIN2_IBLK_MIN       250
#define SETPOINT_UMIN2_IBLK_MAX       5000

#define TIMEOUT_UMIN1_MIN             100
#define TIMEOUT_UMIN1_MAX             32000

#define TIMEOUT_UMIN2_MIN             100
#define TIMEOUT_UMIN2_MAX             32000

#define SETPOINT_UMAX1_MIN            23000
#define SETPOINT_UMAX1_MAX            140000

#define SETPOINT_UMAX2_MIN            23000
#define SETPOINT_UMAX2_MAX            140000

#define TIMEOUT_UMAX1_MIN             0
#define TIMEOUT_UMAX1_MAX             300000

#define TIMEOUT_UMAX2_MIN             0
#define TIMEOUT_UMAX2_MAX             300000

#define SETPOINT_AVR_TN1_U1_UMIN_MIN            10000
#define SETPOINT_AVR_TN1_U1_UMIN_MAX            100000

#define SETPOINT_AVR_TN1_U2_LOW_WORK_MIN        10000
#define SETPOINT_AVR_TN1_U2_LOW_WORK_MAX        100000

#define SETPOINT_AVR_TN2_U2_UMIN_MIN            10000
#define SETPOINT_AVR_TN2_U2_UMIN_MAX            100000

#define SETPOINT_AVR1_TN2_U1_LOW_WORK_MIN       10000
#define SETPOINT_AVR1_TN2_U1_LOW_WORK_MAX       100000

#define SETPOINT_AVR_TN1_U1_UMAX_MIN            100000
#define SETPOINT_AVR_TN1_U1_UMAX_MAX            150000

#define SETPOINT_AVR1_TN1_U2_HIGH_WORK_MIN      100000
#define SETPOINT_AVR1_TN1_U2_HIGH_WORK_MAX      150000

#define SETPOINT_AVR_TN2_U2_UMAX_MIN            100000
#define SETPOINT_AVR_TN2_U2_UMAX_MAX            150000

#define SETPOINT_AVR1_TN2_U1_HIGH_WORK_MIN      100000
#define SETPOINT_AVR1_TN2_U1_HIGH_WORK_MAX      150000

#define TIMEOUT_AVR_GENERAL_BLK_K1_MIN          200
#define TIMEOUT_AVR_GENERAL_BLK_K1_MAX          32000

#define TIMEOUT_AVR_GENERAL_PUSK_K1_MIN         200
#define TIMEOUT_AVR_GENERAL_PUSK_K1_MAX         32000

#define TIMEOUT_AVR_GENERAL_D_DIJI_K1_MIN       200
#define TIMEOUT_AVR_GENERAL_D_DIJI_K1_MAX       32000

#define TIMEOUT_AVR_GENERAL_VVIMK_REZ_K1_MIN    200
#define TIMEOUT_AVR_GENERAL_VVIMK_REZ_K1_MAX    32000

#define TIMEOUT_AVR_GENERAL_VVIMK_K1_MIN        200
#define TIMEOUT_AVR_GENERAL_VVIMK_K1_MAX        32000

#define TIMEOUT_AVR_GENERAL_VYMK_K1_MIN         200
#define TIMEOUT_AVR_GENERAL_VYMK_K1_MAX         32000

#define TIMEOUT_AVR_GENERAL_BLK_K2_MIN          200
#define TIMEOUT_AVR_GENERAL_BLK_K2_MAX          32000

#define TIMEOUT_AVR_GENERAL_PUSK_K2_MIN         200
#define TIMEOUT_AVR_GENERAL_PUSK_K2_MAX         32000

#define TIMEOUT_AVR_GENERAL_D_DIJI_K2_MIN       200
#define TIMEOUT_AVR_GENERAL_D_DIJI_K2_MAX       32000

#define TIMEOUT_AVR_GENERAL_VVIMK_REZ_K2_MIN    200
#define TIMEOUT_AVR_GENERAL_VVIMK_REZ_K2_MAX    32000

#define TIMEOUT_AVR_GENERAL_VVIMK_K2_MIN        200
#define TIMEOUT_AVR_GENERAL_VVIMK_K2_MAX        32000

#define TIMEOUT_AVR_GENERAL_VYMK_K2_MIN         200
#define TIMEOUT_AVR_GENERAL_VYMK_K2_MAX         32000

#define TIMEOUT_AVR_UMIN_VYMK_ROB_K1_MIN        200
#define TIMEOUT_AVR_UMIN_VYMK_ROB_K1_MAX        32000

#define TIMEOUT_AVR_UMIN_VYMK_ROB_K2_MIN        200
#define TIMEOUT_AVR_UMIN_VYMK_ROB_K2_MAX        32000

#define TIMEOUT_AVR_UMAX_VYMK_ROB_K1_MIN        200
#define TIMEOUT_AVR_UMAX_VYMK_ROB_K1_MAX        32000

#define TIMEOUT_AVR_UMAX_VYMK_ROB_K2_MIN        200
#define TIMEOUT_AVR_UMAX_VYMK_ROB_K2_MAX        32000

#define SETPOINT_CTRL_PHASE_U_MIN     100
#define SETPOINT_CTRL_PHASE_U_MAX     50000

#define SETPOINT_CTRL_PHASE_PHI_MIN   1         //формат xy <- x.y, тобто 0.1
#define SETPOINT_CTRL_PHASE_PHI_MAX   450       //формат xy <- x.y, тобто 45.0

#define SETPOINT_CTRL_PHASE_F_MIN     10        //формат xyzl <- x.yzl, тобто 0.010
#define SETPOINT_CTRL_PHASE_F_MAX     5000      //формат xyzl <- x.yzl, тобто 5.000

#define TIMEOUT_CTRL_PHASE_U_MIN      0
#define TIMEOUT_CTRL_PHASE_U_MAX      32000

#define TIMEOUT_CTRL_PHASE_U_D_MIN    0
#define TIMEOUT_CTRL_PHASE_U_D_MAX    32000

#define TIMEOUT_CTRL_PHASE_PHI_MIN    0
#define TIMEOUT_CTRL_PHASE_PHI_MAX    32000

#define TIMEOUT_CTRL_PHASE_PHI_D_MIN  0
#define TIMEOUT_CTRL_PHASE_PHI_D_MAX  32000

#define TIMEOUT_CTRL_PHASE_F_MIN      0
#define TIMEOUT_CTRL_PHASE_F_MAX      32000

#define TIMEOUT_CTRL_PHASE_F_D_MIN    0
#define TIMEOUT_CTRL_PHASE_F_D_MAX    32000

#define SETPOINT_Inom_MIN             5
#define SETPOINT_Inom_MAX             (SETPOINT_Inom_MIN*KOEF_TT_MAX)

#define SETPOINT_RKS_Inom_MIN         1000
#define SETPOINT_RKS_Inom_MAX         100000

#define SETPOINT_Inom_vymk_MIN        100
#define SETPOINT_Inom_vymk_MAX        50000

#define SETPOINT_RKS_Inom_vymk_MIN    10
#define SETPOINT_RKS_Inom_vymk_MAX    999

#define TIMEOUT_SWCH_ON_MIN           150
#define TIMEOUT_SWCH_ON_MAX           5000

#define TIMEOUT_SWCH_OFF_MIN          150
#define TIMEOUT_SWCH_OFF_MAX          5000

#define TIMEOUT_SWCH_UDL_BLK_ON_MIN   0
#define TIMEOUT_SWCH_UDL_BLK_ON_MAX   32000

#define TIMEOUT_PRYVODA_VV_MIN        150
#define TIMEOUT_PRYVODA_VV_MAX        1000

#define KOEF_DOPUSK_DV_POST_MIN       0
#define KOEF_DOPUSK_DV_ZMIN_MIN       20
#define KOEF_DOPUSK_DV_MAX            60

#define TIMEOUT_DEACTIVATION_PASSWORD_OFF       0
#define TIMEOUT_DEACTIVATION_PASSWORD_MIN       30
#define TIMEOUT_DEACTIVATION_PASSWORD_MAX       3600

#define TIMEOUT_NEW_SETTINGS_MIN       60
#define TIMEOUT_NEW_SETTINGS_MAX       3600

#define KOEF_ADDRESS_MIN              1
#define KOEF_ADDRESS_MAX              247

#define MAX_NUMBER_SPEEDS_INTERFACE    7
#define VALUE_SPEED_INTERFACE_MIN      0
#define VALUE_SPEED_INTERFACE_MAX      (MAX_NUMBER_SPEEDS_INTERFACE - 1)

#define MAX_NUMBER_PARE_INTERFACE      3
#define VALUE_PARE_INTERFACE_MIN       0
#define VALUE_PARE_INTERFACE_MAX       (MAX_NUMBER_PARE_INTERFACE - 1)

#define MAX_NUMBER_STOP_BITS_INTERFACE 2
#define VALUE_STOP_BITS_INTERFACE_MIN  0
#define VALUE_STOP_BITS_INTERFACE_MAX  (MAX_NUMBER_STOP_BITS_INTERFACE - 1)

#define VALUE_TIME_OUT_1_INTERFACE_MIN 15
#define VALUE_TIME_OUT_1_INTERFACE_MAX 694

#define VALUE_SETTING_LANGUAGE_MIN    LANGUAGE_RU
#define VALUE_SETTING_LANGUAGE_MAX    LANGUAGE_EN

#define NUMBER_ITERATION_EL_MIN       1
#define NUMBER_ITERATION_EL_MAX       32

#define NUMBER_DEFINED_FUNCTIONS_MIN  0
#define NUMBER_DEFINED_FUNCTIONS_MAX  NUMBER_DEFINED_FUNCTIONS

#define NUMBER_DEFINED_TRIGGERS_MIN   0
#define NUMBER_DEFINED_TRIGGERS_MAX   NUMBER_DEFINED_TRIGGERS

#define NUMBER_DEFINED_AND_MIN        0
#define NUMBER_DEFINED_AND_MAX        NUMBER_DEFINED_AND

#define NUMBER_DEFINED_OR_MIN         0
#define NUMBER_DEFINED_OR_MAX         NUMBER_DEFINED_OR

#define NUMBER_DEFINED_XOR_MIN        0
#define NUMBER_DEFINED_XOR_MAX        NUMBER_DEFINED_XOR

#define NUMBER_DEFINED_NOT_MIN        0
#define NUMBER_DEFINED_NOT_MAX        NUMBER_DEFINED_NOT

#define TIMEOUT_DF_PAUSE_MIN          0
#define TIMEOUT_DF_PAUSE_MAX          300000

#define TIMEOUT_DF_WORK_MIN           0
#define TIMEOUT_DF_WORK_MAX           300000

#define TIMEOUT_PREFAULT_MIN          100
#define TIMEOUT_PREFAULT_MAX          5000

#define TIMEOUT_POSTFAULT_MIN         1000
#define TIMEOUT_POSTFAULT_MAX         25000

#define NUMBER_LINES_FORWARD_MIN      1
#define NUMBER_LINES_BACKWARD_MIN     0
#define NUMBER_LINES_MAX              8

#define SETPOINT_DOVGYNA_VMP_MIN      1
#define SETPOINT_DOVGYNA_VMP_MAX      40000

#define SETPOINT_OPIR_VMP_MIN         1
#define SETPOINT_OPIR_VMP_MAX         20000

#endif
