#ifndef __CONST_MENU_CTRL_PHASE__
#define __CONST_MENU_CTRL_PHASE__

#define EKRAN_SETPOINT_CTRL_PHASE_GROUP1   (EKRAN_SETPOINT_AVR_GROUP4 + 1)
#define EKRAN_SETPOINT_CTRL_PHASE_GROUP2   (EKRAN_SETPOINT_CTRL_PHASE_GROUP1  + 1)
#define EKRAN_SETPOINT_CTRL_PHASE_GROUP3   (EKRAN_SETPOINT_CTRL_PHASE_GROUP2  + 1)
#define EKRAN_SETPOINT_CTRL_PHASE_GROUP4   (EKRAN_SETPOINT_CTRL_PHASE_GROUP3  + 1)
#define EKRAN_TIMEOUT_CTRL_PHASE_GROUP1    (EKRAN_TIMEOUT_AVR_GROUP4  + 1)
#define EKRAN_TIMEOUT_CTRL_PHASE_GROUP2    (EKRAN_TIMEOUT_CTRL_PHASE_GROUP1   + 1)
#define EKRAN_TIMEOUT_CTRL_PHASE_GROUP3    (EKRAN_TIMEOUT_CTRL_PHASE_GROUP2   + 1)
#define EKRAN_TIMEOUT_CTRL_PHASE_GROUP4    (EKRAN_TIMEOUT_CTRL_PHASE_GROUP3   + 1)
#define EKRAN_CONTROL_CTRL_PHASE           (EKRAN_CONTROL_AVR  + 1)

#define MAX_ROW_FOR_SETPOINT_CTRL_PHASE        3
#define MAX_ROW_FOR_TIMEOUT_CTRL_PHASE         5
#define MAX_ROW_FOR_CONTROL_CTRL_PHASE         5

#define INDEX_ML_STPCTRL_PHASE_U               0
#define INDEX_ML_STPCTRL_PHASE_PHI             1
#define INDEX_ML_STPCTRL_PHASE_F               2

#define INDEX_ML_TMOCTRL_PHASE_U               0
#define INDEX_ML_TMOCTRL_PHASE_PHI             1
#define INDEX_ML_TMOCTRL_PHASE_F               2
#define INDEX_ML_TMOCTRL_PHASE_SEQ_TN1         3
#define INDEX_ML_TMOCTRL_PHASE_SEQ_TN2         4

#define COL_SETPOINT_CTRL_PHASE_U_BEGIN        6
#define COL_SETPOINT_CTRL_PHASE_U_COMMA        8
#define COL_SETPOINT_CTRL_PHASE_U_END          9

#define COL_SETPOINT_CTRL_PHASE_PHI_BEGIN      6
#define COL_SETPOINT_CTRL_PHASE_PHI_COMMA      8
#define COL_SETPOINT_CTRL_PHASE_PHI_END        9

#define COL_SETPOINT_CTRL_PHASE_F_BEGIN        6
#define COL_SETPOINT_CTRL_PHASE_F_COMMA        7
#define COL_SETPOINT_CTRL_PHASE_F_END          9

#define COL_SETPOINT_CTRL_PHASE_MAX2_BEGIN     5
#define COL_SETPOINT_CTRL_PHASE_MAX2_COMMA     8
#define COL_SETPOINT_CTRL_PHASE_MAX2_END       9

#define COL_TMO_CTRL_PHASE_BLK_K1_BEGIN        4
#define COL_TMO_CTRL_PHASE_BLK_K1_COMMA        6
#define COL_TMO_CTRL_PHASE_BLK_K1_END          8

#define COL_TMO_CTRL_PHASE_PUSK_K1_BEGIN       4
#define COL_TMO_CTRL_PHASE_PUSK_K1_COMMA       6
#define COL_TMO_CTRL_PHASE_PUSK_K1_END         8

#define COL_TMO_CTRL_PHASE_D_DIJI_K1_BEGIN     4
#define COL_TMO_CTRL_PHASE_D_DIJI_K1_COMMA     6
#define COL_TMO_CTRL_PHASE_D_DIJI_K1_END       8

#define COL_TMO_CTRL_PHASE_VVIMK_REZ_K1_BEGIN  4
#define COL_TMO_CTRL_PHASE_VVIMK_REZ_K1_COMMA  6
#define COL_TMO_CTRL_PHASE_VVIMK_REZ_K1_END    8

#define COL_TMO_CTRL_PHASE_VVIMK_K1_BEGIN      4
#define COL_TMO_CTRL_PHASE_VVIMK_K1_COMMA      6
#define COL_TMO_CTRL_PHASE_VVIMK_K1_END        8

#define COL_TMO_CTRL_PHASE_VYMK_ROB_K1_BEGIN   4
#define COL_TMO_CTRL_PHASE_VYMK_ROB_K1_COMMA   6
#define COL_TMO_CTRL_PHASE_VYMK_ROB_K1_END     8

#define COL_TMO_CTRL_PHASE_VYMK_K1_BEGIN       4
#define COL_TMO_CTRL_PHASE_VYMK_K1_COMMA       6
#define COL_TMO_CTRL_PHASE_VYMK_K1_END         8

#define COL_TMO_CTRL_PHASE_BLK_K2_BEGIN        4
#define COL_TMO_CTRL_PHASE_BLK_K2_COMMA        6
#define COL_TMO_CTRL_PHASE_BLK_K2_END          8

#define COL_TMO_CTRL_PHASE_PUSK_K2_BEGIN       4
#define COL_TMO_CTRL_PHASE_PUSK_K2_COMMA       6
#define COL_TMO_CTRL_PHASE_PUSK_K2_END         8

#define COL_TMO_CTRL_PHASE_D_DIJI_K2_BEGIN     4
#define COL_TMO_CTRL_PHASE_D_DIJI_K2_COMMA     6
#define COL_TMO_CTRL_PHASE_D_DIJI_K2_END       8

#define COL_TMO_CTRL_PHASE_VVIMK_REZ_K2_BEGIN  4
#define COL_TMO_CTRL_PHASE_VVIMK_REZ_K2_COMMA  6
#define COL_TMO_CTRL_PHASE_VVIMK_REZ_K2_END    8

#define COL_TMO_CTRL_PHASE_VVIMK_K2_BEGIN      4
#define COL_TMO_CTRL_PHASE_VVIMK_K2_COMMA      6
#define COL_TMO_CTRL_PHASE_VVIMK_K2_END        8

#define COL_TMO_CTRL_PHASE_VYMK_ROB_K2_BEGIN   4
#define COL_TMO_CTRL_PHASE_VYMK_ROB_K2_COMMA   6
#define COL_TMO_CTRL_PHASE_VYMK_ROB_K2_END     8

#define COL_TMO_CTRL_PHASE_VYMK_K2_BEGIN       4
#define COL_TMO_CTRL_PHASE_VYMK_K2_COMMA       6
#define COL_TMO_CTRL_PHASE_VYMK_K2_END         8

#define INDEX_CTR_CTRL_PHASE                           0
#define CTR_CTRL_PHASE                                 (1 << INDEX_CTR_CTRL_PHASE)
#define INDEX_CTR_CTRL_PHASE_OTKL_BLK                  1
#define CTR_CTRL_PHASE_OTKL_BLK                       (1 << INDEX_CTR_CTRL_PHASE_OTKL_BLK)

#define CTR_CTRL_PHASE_MASKA                           (CTR_CTRL_PHASE                       |\
                                                 CTR_CTRL_PHASE_OTKL_BLK)

#endif
